[[teams]]
name ="Tarjetakuna"
gh_user ="Tarjetakuna"
gh_repo ="Tarjetakuna"

[[teams]]
name ="BeGreen"
gh_user ="SDP-BeGreen"
gh_repo ="BeGreen"

[[teams]]
name ="polypoly"
gh_user ="polypoly-team"
gh_repo ="android-app"

[[teams]]
name ="Orkest"
gh_user ="OrkestApp"
gh_repo ="sdp_2023"

[[teams]]
name ="EPForumL"
gh_user ="EPForumL"
gh_repo ="androidApp"

[[teams]]
name ="DrawYourPath"
gh_user ="DrawYourPath"
gh_repo ="DrawYourPath"

[[teams]]
name ="IBDB"
gh_user ="LEuLuDyHa"
gh_repo ="app"

[[teams]]
name ="CultureQuest"
gh_user ="CultureQuestORG"
gh_repo ="SDP2023"

[[teams]]
name ="ConnectOut"
gh_user ="ConnectOut-sdp"
gh_repo ="sdp2023"

[[teams]]
name ="Coach me"
gh_user ="SDPCoachMe"
gh_repo ="SDP-2023"

[[teams]]
name ="StudyDistractor"
gh_user ="StudyDistractor"
gh_repo ="sdp"

[[teams]]
name ="Versus"
gh_user ="cs306-versus"
gh_repo ="versus-app"

[[teams]]
name ="GeoHunt"
gh_user ="SDP-GeoHunt"
gh_repo ="geo-hunt"

[[teams]]
name ="DishDelish"
gh_user ="DishDelish"
gh_repo ="dishdelish-app"

[[teams]]
name ="Campus Capture"
gh_user ="Campus-Capture"
gh_repo ="campus-capture"

[[teams]]
name ="ScribeWiz"
gh_user ="scribeWiz-team"
gh_repo ="ScribeWiz"

[[teams]]
name ="cook4me"
gh_user ="cook4me"
gh_repo ="android"

[[teams]]
name ="procrastinot"
gh_user ="procrastinot-team"
gh_repo ="procrastinot"

[[teams]]
name ="MediaTo"
gh_user ="MediaTo-SDP"
gh_repo ="MediaTo"

[[teams]]
name ="Guess It"
gh_user ="guess-It-SDP"
gh_repo ="guessIt"

[[teams]]
name ="Stud'Hub"
gh_user ="studhub-epfl"
gh_repo ="studhub-app"

[[teams]]
name ="Factotum"
gh_user ="Factotum-sdp"
gh_repo ="Factotum"
